### ISSUE TITLE
Re-write checking `dep_inv`, `lat_inv`, and `lon_inv` from `input_params.cpp`

### ISSUE THREAD

**Issue by xumi1993** [TomoATT/TomoATT#5]
@TomoATT/developer  In the current version, if the `uniform_inv_grid_dep` is used without the `config["model_update"]["dep_inv"]` parameter being defined, an error 'dep_inv is not defined. Stop.' will be raised. This error should be suppressed when using a uniform inversion grid.

**Comment by JingChen-Thu** [comment]
@xumi1993 This issue is addressed in this pull request:
https://github.com/TomoATT/TomoATT/pull/6
